
export const alphabetRus = [
  {letter: 'Аа', image: require('../assets/cards/1.png'), voiceWord: require('../assets/voices/words/1.mp3'), voiceLetter: require('../assets/voices/letters/1.mp3') },
  {letter: 'Бб', image: require('../assets/cards/2.png'), voiceWord: require('../assets/voices/words/2.mp3'), voiceLetter: require('../assets/voices/letters/2.mp3') },
  {letter: 'Вв', image: require('../assets/cards/3.png'), voiceWord: require('../assets/voices/words/3.mp3'), voiceLetter: require('../assets/voices/letters/3.mp3') },
  {letter: 'Гг', image: require('../assets/cards/4.png'), voiceWord: require('../assets/voices/words/4.mp3'), voiceLetter: require('../assets/voices/letters/4.mp3') },
  {letter: 'Дд', image: require('../assets/cards/5.png'), voiceWord: require('../assets/voices/words/5.mp3'), voiceLetter: require('../assets/voices/letters/5.mp3') },
  {letter: 'Ее', image: require('../assets/cards/6.png'), voiceWord: require('../assets/voices/words/6.mp3'), voiceLetter: require('../assets/voices/letters/6.mp3') },
  {letter: 'Ёё', image: require('../assets/cards/7.png'), voiceWord: require('../assets/voices/words/7.mp3'), voiceLetter: require('../assets/voices/letters/7.mp3') },
  {letter: 'Жж', image: require('../assets/cards/8.png'), voiceWord: require('../assets/voices/words/8.mp3'), voiceLetter: require('../assets/voices/letters/8.mp3') },
  {letter: 'Зз', image: require('../assets/cards/9.png'), voiceWord: require('../assets/voices/words/9.mp3'), voiceLetter: require('../assets/voices/letters/9.mp3') },
  {letter: 'Ии', image: require('../assets/cards/10.png'), voiceWord: require('../assets/voices/words/10.mp3'), voiceLetter: require('../assets/voices/letters/10.mp3') },
  {letter: 'Йй', image: require('../assets/cards/11.png'), voiceWord: require('../assets/voices/words/11.mp3'), voiceLetter: require('../assets/voices/letters/11.mp3') },
  {letter: 'Кк', image: require('../assets/cards/12.png'), voiceWord: require('../assets/voices/words/12.mp3'), voiceLetter: require('../assets/voices/letters/12.mp3') },
  {letter: 'Лл', image: require('../assets/cards/13.png'), voiceWord: require('../assets/voices/words/13.mp3'), voiceLetter: require('../assets/voices/letters/13.mp3') },
  {letter: 'Мм', image: require('../assets/cards/14.png'), voiceWord: require('../assets/voices/words/14.mp3'), voiceLetter: require('../assets/voices/letters/14.mp3') },
  {letter: 'Нн', image: require('../assets/cards/15.png'), voiceWord: require('../assets/voices/words/15.mp3'), voiceLetter: require('../assets/voices/letters/15.mp3') },
  {letter: 'Оо', image: require('../assets/cards/16.png'), voiceWord: require('../assets/voices/words/16.mp3'), voiceLetter: require('../assets/voices/letters/16.mp3') },
  {letter: 'Пп', image: require('../assets/cards/17.png'), voiceWord: require('../assets/voices/words/17.mp3'), voiceLetter: require('../assets/voices/letters/17.mp3') },
  {letter: 'Рр', image: require('../assets/cards/18.png'), voiceWord: require('../assets/voices/words/18.mp3'), voiceLetter: require('../assets/voices/letters/18.mp3') },
  {letter: 'Сс', image: require('../assets/cards/19.png'), voiceWord: require('../assets/voices/words/19.mp3'), voiceLetter: require('../assets/voices/letters/19.mp3') },
  {letter: 'Тт', image: require('../assets/cards/20.png'), voiceWord: require('../assets/voices/words/20.mp3'), voiceLetter: require('../assets/voices/letters/20.mp3') },
  {letter: 'Уу', image: require('../assets/cards/21.png'), voiceWord: require('../assets/voices/words/21.mp3'), voiceLetter: require('../assets/voices/letters/21.mp3') },
  {letter: 'Фф', image: require('../assets/cards/22.png'), voiceWord: require('../assets/voices/words/22.mp3'), voiceLetter: require('../assets/voices/letters/22.mp3') },
  {letter: 'Хх', image: require('../assets/cards/23.png'), voiceWord: require('../assets/voices/words/23.mp3'), voiceLetter: require('../assets/voices/letters/23.mp3') },
  {letter: 'Цц', image: require('../assets/cards/24.png'), voiceWord: require('../assets/voices/words/24.mp3'), voiceLetter: require('../assets/voices/letters/24.mp3') },
  {letter: 'Чч', image: require('../assets/cards/25.png'), voiceWord: require('../assets/voices/words/25.mp3'), voiceLetter: require('../assets/voices/letters/25.mp3') },
  {letter: 'Шш', image: require('../assets/cards/26.png'), voiceWord: require('../assets/voices/words/26.mp3'), voiceLetter: require('../assets/voices/letters/26.mp3') },
  {letter: 'Щщ', image: require('../assets/cards/27.png'), voiceWord: require('../assets/voices/words/27.mp3'), voiceLetter: require('../assets/voices/letters/27.mp3') },
  {letter: 'ъ', image: require('../assets/cards/28.png'), voiceWord: require('../assets/voices/words/28.mp3'), voiceLetter: require('../assets/voices/letters/28.mp3') },
  {letter: 'ы', image: require('../assets/cards/29.png'), voiceWord: require('../assets/voices/words/29.mp3'), voiceLetter: require('../assets/voices/letters/29.mp3') },
  {letter: 'ь', image: require('../assets/cards/30.png'), voiceWord: require('../assets/voices/words/30.mp3'), voiceLetter: require('../assets/voices/letters/30.mp3') },
  {letter: 'Ээ', image: require('../assets/cards/31.png'), voiceWord: require('../assets/voices/words/31.mp3'), voiceLetter: require('../assets/voices/letters/31.mp3') },
  {letter: 'Юю', image: require('../assets/cards/32.png'), voiceWord: require('../assets/voices/words/32.mp3'), voiceLetter: require('../assets/voices/letters/32.mp3') },
  {letter: 'Яя', image: require('../assets/cards/33.png'), voiceWord: require('../assets/voices/words/33.mp3'), voiceLetter: require('../assets/voices/letters/33.mp3') }
];

export const find = [
  {findLetter: require('../assets/voices/findLetter/1.mp3')},
  {findLetter: require('../assets/voices/findLetter/2.mp3')},
  {findLetter: require('../assets/voices/findLetter/3.mp3')},
  {findLetter: require('../assets/voices/findLetter/4.mp3')},
  {findLetter: require('../assets/voices/findLetter/5.mp3')},
  {findLetter: require('../assets/voices/findLetter/6.mp3')},
  {findLetter: require('../assets/voices/findLetter/7.mp3')},
  {findLetter: require('../assets/voices/findLetter/8.mp3')},
  {findLetter: require('../assets/voices/findLetter/9.mp3')},
  {findLetter: require('../assets/voices/findLetter/10.mp3')},
  {findLetter: require('../assets/voices/findLetter/11.mp3')},
  {findLetter: require('../assets/voices/findLetter/12.mp3')},
  {findLetter: require('../assets/voices/findLetter/13.mp3')},
  {findLetter: require('../assets/voices/findLetter/14.mp3')},
  {findLetter: require('../assets/voices/findLetter/15.mp3')},
  {findLetter: require('../assets/voices/findLetter/16.mp3')},
  {findLetter: require('../assets/voices/findLetter/17.mp3')},
  {findLetter: require('../assets/voices/findLetter/18.mp3')},
  {findLetter: require('../assets/voices/findLetter/19.mp3')},
  {findLetter: require('../assets/voices/findLetter/20.mp3')},
  {findLetter: require('../assets/voices/findLetter/21.mp3')},
  {findLetter: require('../assets/voices/findLetter/22.mp3')},
  {findLetter: require('../assets/voices/findLetter/23.mp3')},
  {findLetter: require('../assets/voices/findLetter/24.mp3')},
  {findLetter: require('../assets/voices/findLetter/25.mp3')},
  {findLetter: require('../assets/voices/findLetter/26.mp3')},
  {findLetter: require('../assets/voices/findLetter/27.mp3')},
  {findLetter: require('../assets/voices/findLetter/28.mp3')},
  {findLetter: require('../assets/voices/findLetter/29.mp3')},
  {findLetter: require('../assets/voices/findLetter/30.mp3')},
  {findLetter: require('../assets/voices/findLetter/31.mp3')},
  {findLetter: require('../assets/voices/findLetter/32.mp3')},
  {findLetter: require('../assets/voices/findLetter/33.mp3')}
];

export const alphabetEng = [
  {letter: 'Aa', image: require('../assets/cardsEng/1.png'), voiceWord: require('../assets/voices/wordsEng/1.mp3'), voiceLetter: require('../assets/voices/lettersEng/1.mp3') },
  {letter: 'Bb', image: require('../assets/cardsEng/2.png'), voiceWord: require('../assets/voices/wordsEng/2.mp3'), voiceLetter: require('../assets/voices/lettersEng/2.mp3') },
  {letter: 'Cc', image: require('../assets/cardsEng/3.png'), voiceWord: require('../assets/voices/wordsEng/3.mp3'), voiceLetter: require('../assets/voices/lettersEng/3.mp3') },
  {letter: 'Dd', image: require('../assets/cardsEng/4.png'), voiceWord: require('../assets/voices/wordsEng/4.mp3'), voiceLetter: require('../assets/voices/lettersEng/4.mp3') },
  {letter: 'Ee', image: require('../assets/cardsEng/5.png'), voiceWord: require('../assets/voices/wordsEng/5.mp3'), voiceLetter: require('../assets/voices/lettersEng/5.mp3') },
  {letter: 'Ff', image: require('../assets/cardsEng/6.png'), voiceWord: require('../assets/voices/wordsEng/6.mp3'), voiceLetter: require('../assets/voices/lettersEng/6.mp3') },
  {letter: 'Gg', image: require('../assets/cardsEng/7.png'), voiceWord: require('../assets/voices/wordsEng/7.mp3'), voiceLetter: require('../assets/voices/lettersEng/7.mp3') },
  {letter: 'Hh', image: require('../assets/cardsEng/8.png'), voiceWord: require('../assets/voices/wordsEng/8.mp3'), voiceLetter: require('../assets/voices/lettersEng/8.mp3') },
  {letter: 'Ii', image: require('../assets/cardsEng/9.png'), voiceWord: require('../assets/voices/wordsEng/9.mp3'), voiceLetter: require('../assets/voices/lettersEng/9.mp3') },
  {letter: 'Jj', image: require('../assets/cardsEng/10.png'), voiceWord: require('../assets/voices/wordsEng/10.mp3'), voiceLetter: require('../assets/voices/lettersEng/10.mp3') },
  {letter: 'Kk', image: require('../assets/cardsEng/11.png'), voiceWord: require('../assets/voices/wordsEng/11.mp3'), voiceLetter: require('../assets/voices/lettersEng/11.mp3') },
  {letter: 'Ll', image: require('../assets/cardsEng/12.png'), voiceWord: require('../assets/voices/wordsEng/12.mp3'), voiceLetter: require('../assets/voices/lettersEng/12.mp3') },
  {letter: 'Mm', image: require('../assets/cardsEng/13.png'), voiceWord: require('../assets/voices/wordsEng/13.mp3'), voiceLetter: require('../assets/voices/lettersEng/13.mp3') },
  {letter: 'Nn', image: require('../assets/cardsEng/14.png'), voiceWord: require('../assets/voices/wordsEng/14.mp3'), voiceLetter: require('../assets/voices/lettersEng/14.mp3') },
  {letter: 'Oo', image: require('../assets/cardsEng/15.png'), voiceWord: require('../assets/voices/wordsEng/15.mp3'), voiceLetter: require('../assets/voices/lettersEng/15.mp3') },
  {letter: 'Pp', image: require('../assets/cardsEng/16.png'), voiceWord: require('../assets/voices/wordsEng/16.mp3'), voiceLetter: require('../assets/voices/lettersEng/16.mp3') },
  {letter: 'Qq', image: require('../assets/cardsEng/17.png'), voiceWord: require('../assets/voices/wordsEng/17.mp3'), voiceLetter: require('../assets/voices/lettersEng/17.mp3') },
  {letter: 'Rr', image: require('../assets/cardsEng/18.png'), voiceWord: require('../assets/voices/wordsEng/18.mp3'), voiceLetter: require('../assets/voices/lettersEng/18.mp3') },
  {letter: 'Ss', image: require('../assets/cardsEng/19.png'), voiceWord: require('../assets/voices/wordsEng/19.mp3'), voiceLetter: require('../assets/voices/lettersEng/19.mp3') },
  {letter: 'Tt', image: require('../assets/cardsEng/20.png'), voiceWord: require('../assets/voices/wordsEng/20.mp3'), voiceLetter: require('../assets/voices/lettersEng/20.mp3') },
  {letter: 'Uu', image: require('../assets/cardsEng/21.png'), voiceWord: require('../assets/voices/wordsEng/21.mp3'), voiceLetter: require('../assets/voices/lettersEng/21.mp3') },
  {letter: 'Vv', image: require('../assets/cardsEng/22.png'), voiceWord: require('../assets/voices/wordsEng/22.mp3'), voiceLetter: require('../assets/voices/lettersEng/22.mp3') },
  {letter: 'Ww', image: require('../assets/cardsEng/23.png'), voiceWord: require('../assets/voices/wordsEng/23.mp3'), voiceLetter: require('../assets/voices/lettersEng/23.mp3') },
  {letter: 'Xx', image: require('../assets/cardsEng/24.png'), voiceWord: require('../assets/voices/wordsEng/24.mp3'), voiceLetter: require('../assets/voices/lettersEng/24.mp3') },
  {letter: 'Yy', image: require('../assets/cardsEng/25.png'), voiceWord: require('../assets/voices/wordsEng/25.mp3'), voiceLetter: require('../assets/voices/lettersEng/25.mp3') },
  {letter: 'Zz', image: require('../assets/cardsEng/26.png'), voiceWord: require('../assets/voices/wordsEng/26.mp3'), voiceLetter: require('../assets/voices/lettersEng/26.mp3') },
];
